apiVersion: v1
kind: Pod
metadata:
  name: psql
  labels:
    tier: database
spec:
  containers:
    - name: psql
      image: 'postgres'
      env:
        - name: POSTGRES_PASSWORD
          value: usman123
